export const provinces = [
  { province: 'Batangas', province_code: 'BTG' },
  { province: 'Cavite', province_code: 'CAV' },
  { province: 'Laguna', province_code: 'LAG' },
  { province: 'Quezon', province_code: 'QUE' },
  { province: 'Rizal', province_code: 'RIZ' }
]

export const muncities = [
	{ muncity: 'Agoncillo', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Alitagtag', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Balayan', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Balete', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Batangas', province: 'Batangas', province_code: 'BTG', city: true },
  { muncity: 'Bauan', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Calaca', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Calatagan', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Cuenca', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Ibaan', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Laurel', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Lemery', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Lian', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Lipa', province: 'Batangas', province_code: 'BTG', city: true },
  { muncity: 'Lobo', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Mabini', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Malvar', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Mataasnakahoy', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Nasugbu', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Padre Garcia', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Rosario', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'San Jose', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'San Juan', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'San Luis', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'San Nicolas', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'San Pascual', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Santa Teresita', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Santo Tomas', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Taal', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Talisay', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Tanauan', province: 'Batangas', province_code: 'BTG', city: true },
  { muncity: 'Taysan', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Tingloy', province: 'Batangas', province_code: 'BTG' },
  { muncity: 'Tuy', province: 'Batangas', province_code: 'BTG' },

  { muncity: 'Alfonso', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Amadeo', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Bacoor', province: 'Cavite', province_code: 'CAV', city: true },
  { muncity: 'Carmona', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Cavite', province: 'Cavite', province_code: 'CAV', city: true },
  { muncity: 'Dasmariñas', province: 'Cavite', province_code: 'CAV', city: true },
  { muncity: 'General Mariano Alvarez', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'General Emilio Aguinaldo', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'General Trias', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Imus', province: 'Cavite', province_code: 'CAV', city: true },
  { muncity: 'Indang', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Kawit', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Magallanes', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Maragondon', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Mendez', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Naic', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Noveleta', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Rosario', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Silang', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Tagaytay', province: 'Cavite', province_code: 'CAV', city: true },
  { muncity: 'Tanza', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Ternate', province: 'Cavite', province_code: 'CAV' },
  { muncity: 'Trece Martires', province: 'Cavite', province_code: 'CAV', city: true },

  { muncity: 'Alaminos', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Bay', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Biñan', province: 'Laguna', province_code: 'LAG', city: true },
  { muncity: 'Cabuyao', province: 'Laguna', province_code: 'LAG', city: true },
  { muncity: 'Calamba', province: 'Laguna', province_code: 'LAG', city: true },
  { muncity: 'Calauan', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Cavinti', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Famy', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Kalayaan', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Liliw', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Los Baños', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Luisiana', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Lumban', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Mabitac', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Magdalena', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Majayjay', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Nagcarlan', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Paete', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Pagsanjan', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Pakil', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Pangil', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Pila', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Rizal', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'San Pablo', province: 'Laguna', province_code: 'LAG', city: true },
  { muncity: 'San Pedro', province: 'Laguna', province_code: 'LAG', city: true },
  { muncity: 'Santa Cruz', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Santa Maria', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Santa Rosa', province: 'Laguna', province_code: 'LAG', city: true },
  { muncity: 'Siniloan', province: 'Laguna', province_code: 'LAG' },
  { muncity: 'Victoria', province: 'Laguna', province_code: 'LAG' },

  { muncity: 'Agdangan', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Alabat', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Atimonan', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Buenavista', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Burdeos', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Calauag', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Candelaria', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Catanauan', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Dolores', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'General Luna', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'General Nakar', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Guinayangan', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Gumaca', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Infanta', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Jomalig', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Lopez', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Lucban', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Lucena', province: 'Quezon', province_code: 'QUE', city: true },
  { muncity: 'Macalelon', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Mauban', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Mulanay', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Padre Burgos', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Pagbilao', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Panukulan', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Patnanungan', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Perez', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Pitogo', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Plaridel', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Polillo', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Quezon', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Real', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Sampaloc', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'San Andres', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'San Antonio', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'San Francisco', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'San Narciso', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Sariaya', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Tagkawayan', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Tayabas', province: 'Quezon', province_code: 'QUE', city: true },
  { muncity: 'Tiaong', province: 'Quezon', province_code: 'QUE' },
  { muncity: 'Unisan', province: 'Quezon', province_code: 'QUE' },

  { muncity: 'Angono', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Antipolo', province: 'Rizal', province_code: 'RIZ', city: true },
  { muncity: 'Baras', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Binangonan', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Cainta', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Cardona', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Jalajala', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Morong', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Pililla', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Rodriguez', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'San Mateo', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Tanay', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Taytay', province: 'Rizal', province_code: 'RIZ' },
  { muncity: 'Teresa', province: 'Rizal', province_code: 'RIZ' },
]